### ISSUE TITLE
Fails with virtualenv

### ISSUE THREAD

**Issue by rpgoldman** [m-rossi/jupyter-docx-bundler#15] opened 2019-04-15 17:51 UTC
I have installed jupyter-docx-bundler in a virtual environment and activated it.

However, it seems not to work:

1. When I install nbconvert, it does *not* install the `nbconvert` binary. There is a `jupyter-nbconvert` though, so I tried that.

2. Even though I followed the installation instructions and did:

    ```
     $ jupyter bundlerextension enable --py jupyter_docx_bundler --sys-prefix
     Enabling docx_bundler bundler jupyter_docx_bundler...
    ```

   I see this:
    ```
      $ jupyter-nbconvert --execute --to=docx Simple\ Time\ Series.ipynb --output Simple\ Time\ Series.docx
    Traceback (most recent call last):
      File "/Users/rpg/.virtualenvs/time-series-stats/bin/jupyter-nbconvert", line 10, in <module>
        sys.exit(main())
      File "/Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
        app.start()
      File "/Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 337, in start  self.convert_notebooks()
      File "/Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 496, in convert_notebooks
        cls = get_exporter(self.export_format)
      File "/Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 113, in get_exporter
        % (name, ', '.join(get_export_names())))
    ValueError: Unknown exporter "docx", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
    ```
   However, the package is installed:

    ```
    $ find ~/.virtualenvs/time-series-stats/ -name 'jupyter_docx_bundler*'
    /Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/jupyter_docx_bundler
    /Users/rpg/.virtualenvs/time-series-stats/lib/python3.7/site-packages/jupyter_docx_bundler-0.1.3.dist-info
    (time-series-stats) rpg@RPG-MacBook-Pro: ~/projects/solar-guard/learning $ 
    ```

So it looks like the installation didn't work right.  Is there any chance that the installation process doesn't "understand" virtual environments?

**Comment by rpgoldman** [comment] 2019-04-15 17:54
This adds some confusion to the mix:

```
$ jupyter bundlerextension list
Known bundlerextensions:
  config dir: /Users/rpg/.virtualenvs/time-series-stats/bin/../etc/jupyter/nbconfig
    "Office Open XML (.docx)" from jupyter_docx_bundler  enabled 
```

**Comment by m-rossi** [comment] 2019-04-15 19:43
To be honest, I do not use virtual environments for my personal and work projects, but I thought everything should be correctly set by the parameter `--sys-prefix`, but I have not tested it on my own for virtual environments. However your second comment shows that the jupyter configuration is stored in your virtual environment.

I will try to reproduce your issue on the weekend and report back, thanks for the report @rpgoldman!

**Comment by rpgoldman** [comment] 2019-04-16 14:52
Interestingly, I *was* able to do the conversion from the jupyter notebook web page.  I was just not able to do the conversion from the command line.

I notice also that printing a pandas data frame in docx format does not work well -- instead of getting a table, I get each *cell* of the data frame on a separate line.  E.g., I see this:
```
Out[28]:
vC1
vC2
vOut
R3
R3_norm
C1_pos
C2_pos
vOut_meas
predicted
residual
date
2019-01-01 00:00:00.200
585.51
198.2100
198.4200
19.865
0.50786
1
1
196.450
198.4200
0.0
2019-01-01 00:00:00.201
-342.19
256.1400
256.1600
19.867
```
...and so on.  Is this a known issue? Is it worth filing another issue?  It seems like pandoc should be able to make a docx table out of this, but perhaps it is confused by the special layout that jupyter applies to data frames?

**Comment by m-rossi** [comment] 2019-04-16 16:52
Yes, please file an issue and attach your code that I exactly can reproduce it.

I think pandas Tables were working before. But maybe something in the conversion chain broke since my tests.

**Comment by kirschma** [comment] 2019-04-17 05:19
Hi both,

take care that I have some problems since version 2.7 of pandas. Images are converted correctly in versions <2.6. Since version 2.7 only the first image is converted. I couldn't find the reason yet. The behavior is the same when converting directly from html to docs using pandas!

Martin
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 16.04.19, 18:52, Marco Rossi <notifications@github.com> schrieb:
Yes, please file an issue and attach your code that I exactly can reproduce it.
I think pandas Tables were working before. But maybe something in the conversion chain broke since my tests.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/m-rossi/jupyter-docx-bundler","title":"m-rossi/jupyter-docx-bundler","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/m-rossi/jupyter-docx-bundler"}},"updates":{"snippets":[{"icon":"PERSON","message":"@m-rossi in #15: Yes, please file an issue and attach your code that I exactly can reproduce it.\n\nI think pandas Tables were working before. But maybe something in the conversion chain broke since my tests."}],"action":{"name":"View Issue","url":"https://github.com/m-rossi/jupyter-docx-bundler/issues/15#issuecomment-483756068"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/m-rossi/jupyter-docx-bundler/issues/15#issuecomment-483756068",
"url": "https://github.com/m-rossi/jupyter-docx-bundler/issues/15#issuecomment-483756068",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by m-rossi** [comment] 2019-04-17 07:03
Ok, sounds like I need to improve my testing

**Comment by m-rossi** [comment] 2019-04-22 11:37
@rpgoldman I tried to reproduce your issue on my system (macOS with Python 3.7.3, installed through Anaconda) and created a virtual environment `issue-15` with
```
python -m venv issue-15
source issue-15/bin/activate
```
and installed `jupyter-docx-bundler` with
```
pip install .
```
and afterwards tried to convert a notebook with
```
jupyter-nbconvert --execute --to=docx Untitled.ipynb --output Untitled.docx
```
which resulted in the following _expected_ error:
```
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.
```
I followed the instructions on https://github.com/bebraw/pypandoc#installing-pandoc and pandoc was installed in my applications folder: `/Users/.../Applications/pandoc`. After appending this folder to the path the conversion works fine.

I documented my approach in detail that you can find differences to yours.

**Comment by m-rossi** [comment] 2019-04-28 14:44
Just tested, pandas (html-)tables are converted correctly to a table in the docx-file.

**Comment by m-rossi** [comment] 2019-06-21 12:23
Closing for now, reopen if the problem with venvs still exists on your machine.

**Closed by m-rossi** 2019-06-21 12:23 UTC
